# Generated by Django 6.0.5 on 2026-05-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł pracy')),
                ('author', models.CharField(max_length=100, verbose_name='Autor (Imię i nazwisko)')),
                ('semester', models.CharField(choices=[('sem3', 'Semestr 3'), ('sem4', 'Semestr 4')], max_length=10, verbose_name='Semestr')),
                ('youtube_id', models.CharField(max_length=20, verbose_name='ID wideo z YouTube (np. WhWc3b3KhnY)')),
                ('description', models.TextField(verbose_name='Opis projektu')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Praca studencka',
                'verbose_name_plural': 'Prace studenckie',
            },
        ),
    ]
