# Generated by Django 6.0.5 on 2026-05-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Praca',
            new_name='Artwork',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
