# Generated by Django 6.0.5 on 2026-05-31 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_praca_artwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/images'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='artworks/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID wideo z YouTube (np. WhWc3b3KhnY)'),
        ),
    ]
