# Generated by Django 6.0.5 on 2026-05-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artwork_image_artwork_video_alter_artwork_youtube_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='youtube_id',
            new_name='youtube_link',
        ),
    ]
