# Generated by Django 6.0.5 on 2026-06-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_artwork_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='academic_year',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], default='2025/2026', max_length=9),
        ),
    ]
